Repository mozilla-spidermonkey/jsparagus, pull requests merged in 2020-06, with the labels that each got.

#517 Remove unused alias set fields from actions.
  jsparagus/actions.py
  jsparagus/lr0.py
Labels: parser generator

#533 Rename is_term_shifted to term_is_shifted like term_is_stacked.
  jsparagus/aps.py
  jsparagus/parse_table.py
Labels: parser generator

#513 Replace Term enum by a simple number.
  crates/parser/src/parser.rs
  crates/parser/src/simulator.rs
  jsparagus/emit/rust.py
Labels: optimization, parser generator

#530 Rewrite states within Actions.
  jsparagus/actions.py
  jsparagus/aps.py
  jsparagus/emit/python.py
  jsparagus/parse_table.py
Labels: parser generator

#545 Use bumpalo 3.4.0 (fixes #544)
  Cargo.lock
  crates/ast/Cargo.toml
  crates/driver/Cargo.toml
  crates/driver/src/demo.rs
  crates/emitter/Cargo.toml
  crates/generated_parser/Cargo.toml
  crates/interpreter/Cargo.toml
  crates/interpreter/src/tests.rs
  crates/parser/Cargo.toml
Labels: affects smoosh

#548 Add isdisjoint to OrderedSet and OrderedDrozenSet.
  jsparagus/ordered.py
Labels: parser generator

#547 Distinguish Action.update_stack from Action.follow_edge.
  jsparagus/actions.py
  jsparagus/aps.py
  jsparagus/emit/python.py
  jsparagus/emit/rust.py
  jsparagus/lr0.py
  jsparagus/parse_table.py
Labels: parser generator

#553 Split action function
  jsparagus/emit/rust.py
  jsparagus/parse_table.py
  jsparagus/utils.py
Labels: optimization, parser generator

#560 Move the ParserTrait out of the generated code.
  crates/generated_parser/src/lib.rs
  crates/generated_parser/src/traits/mod.rs
  jsparagus/emit/rust.py
Labels: parser generator

#565 Merge ScriptStencilBase, ScriptStencil, and FunctionStencil, and split bytecode into ImmutableScriptData (fixes #554)
  crates/driver/src/demo.rs
  crates/emitter/src/ast_emitter.rs
  crates/emitter/src/compilation_info.rs
  crates/emitter/src/emitter.rs
  crates/emitter/src/function_declaration_emitter.rs
  crates/emitter/src/lib.rs
  crates/interpreter/src/evaluate.rs
  crates/scope/src/builder.rs
  crates/scope/src/data.rs
  crates/scope/src/pass.rs
  crates/stencil/src/function.rs
  crates/stencil/src/gcthings.rs
  crates/stencil/src/result.rs
  crates/stencil/src/scope.rs
  crates/stencil/src/script.rs
Labels: affects smoosh

#562 Add FilterState action.
  crates/generated_parser/src/traits/mod.rs
  crates/parser/src/parser.rs
  crates/parser/src/simulator.rs
  jsparagus/actions.py
  jsparagus/aps.py
  jsparagus/emit/python.py
  jsparagus/emit/rust.py
  jsparagus/parse_table.py
  jsparagus/runtime.py
Labels: parser generator

#576 Add replay action
  crates/generated_parser/src/traits/mod.rs
  crates/parser/src/parser.rs
  crates/parser/src/queue_stack.rs
  crates/parser/src/simulator.rs
  jsparagus/actions.py
  jsparagus/aps.py
  jsparagus/emit/python.py
  jsparagus/emit/rust.py
  jsparagus/runtime.py
Labels: parser generator
