Repository mozilla-spidermonkey/jsparagus, pull requests merged in 2020-07, with the labels that each got.

#580 Update opcode
  crates/emitter/src/emitter.rs
  crates/stencil/src/copy/BytecodeFormatFlags.h
  crates/stencil/src/copy/Opcodes.h
  crates/stencil/src/opcode.rs
Labels: affects smoosh

#584 Add smoosh_tools bench command.
  benchmarks/compare-spidermonkey-parsers.js
  src/bin/smoosh_tools.rs
Labels: affects smoosh

#587 Avoid allocation by baking-in current lookahead range in the simulator.
  Cargo.lock
  crates/parser/Cargo.toml
  crates/parser/src/lib.rs
  crates/parser/src/simulator.rs
Labels: optimization

#583 Add function_has_extensible_scope to extra body var scope
  crates/scope/src/builder.rs
  crates/stencil/src/scope.rs
Labels: affects smoosh

#578 Optimize with filter and replay
  jsparagus/actions.py
  jsparagus/aps.py
  jsparagus/parse_pgen_generated.py
  jsparagus/parse_table.py
Labels: optimization, parser generator

#596 Add real-js-samples benchmark CI.
  .github/workflows/real-js-benchmark.yml
  src/bin/smoosh_tools.rs
Labels: optimization

#599 Pre-allocate SourceAtomSet to cover 75% of the loaded scripts.
  crates/ast/src/source_atom_set.rs
Labels: optimization

#600 Fold Replay and Unwind action.
  jsparagus/actions.py
  jsparagus/parse_table.py
Labels: optimization

#605 Prepare top level script extent
  Cargo.lock
  crates/driver/Cargo.toml
  crates/driver/src/demo.rs
  crates/emitter/src/ast_emitter.rs
  crates/emitter/src/emitter.rs
  crates/emitter/src/lib.rs
  crates/interpreter/src/tests.rs
  crates/stencil/src/script.rs
  gecko-patches.txt
Labels: affects smoosh

#608 Add state arguments for replay
  jsparagus/actions.py
  jsparagus/aps.py
  jsparagus/emit/python.py
  jsparagus/emit/rust.py
  jsparagus/parse_pgen_generated.py
  jsparagus/parse_table.py
Labels: optimization, parser generator

#609 Remove duplicates in python default methods.
  jsparagus/emit/python.py
  jsparagus/parse_pgen_generated.py
Labels: parser generator
